title: NULL on error
tagline: flipping bits whilst updating pixels
url: https://nullonerror.org
author: skhaz
baseurl: ""
permalink: pretty

analytics: UA-28518341-1

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Rodrigo Delduca
  url: https://skhaz.io/
  email: rodrigodelduca@gmail.com

kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
