title: NULL on error
tagline: flipping bits whilst updating pixels
author: skhaz
url: https://nullonerror.org
analytics: UA-28518341-1
permalink: pretty
baseurl: ""

sass:
  sass_dir: _sass
  style: :compressed

twitter:
  username: nullonerror

kramdown:
  input: GFM

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
