permalink:           pretty

title: NULL on error
tagline: flipping bits whilst updating pixels
url: https://nullonerror.org
analytics: UA-28518341-1
baseurl: ""

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Rodrigo Delduca
  url: https://github.com/skhaz
  email: rodrigodelduca@gmail.com

kramdown:
  input: GFM

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
